<?xml version="1.0" encoding="utf-8" ?>
<dwsync>
<file name="manager.py" server="192.168.133.129//mnt/WEB/internal/SATA/testing/CT/internal/a2billing/" local="130873080380000000" remote="130873080380000000" Dst="1" />
<file name="database.py" server="192.168.133.129//mnt/WEB/internal/SATA/testing/CT/internal/a2billing/" local="130873080380000000" remote="130873080380000000" Dst="1" />
<file name="daemon.py" server="192.168.133.129//mnt/WEB/internal/SATA/testing/CT/internal/a2billing/" local="130873080380000000" remote="130873080380000000" Dst="1" />
<file name="a2b_callback_daemon.py" server="192.168.133.129//mnt/WEB/internal/SATA/testing/CT/internal/a2billing/" local="130873080380000000" remote="130873080380000000" Dst="1" />
<file name="a2b-callback-daemon.rc" server="192.168.133.129//mnt/WEB/internal/SATA/testing/CT/internal/a2billing/" local="130873080380000000" remote="130873080380000000" Dst="1" />
<file name="a2b-callback-daemon.gentoo" server="192.168.133.129//mnt/WEB/internal/SATA/testing/CT/internal/a2billing/" local="130873080380000000" remote="130873080380000000" Dst="1" />
<file name="a2b-callback-daemon.debian" server="192.168.133.129//mnt/WEB/internal/SATA/testing/CT/internal/a2billing/" local="130873080380000000" remote="130873080380000000" Dst="1" />
<file name="__init__.py" server="192.168.133.129//mnt/WEB/internal/SATA/testing/CT/internal/a2billing/" local="130873080380000000" remote="130873080380000000" Dst="1" />
</dwsync>